# Generated by Django 5.2.1 on 2025-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('beauty', 'Beauty'), ('cleaning', 'Cleaning'), ('pet_care', 'Pet Care'), ('car_care', 'Car Care'), ('errands', 'Errands'), ('handyman', 'Handyman')], default='beauty', max_length=20),
        ),
    ]
