# Generated by Django 5.2.1 on 2025-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('beauty_hair', 'Beauty - Hair'), ('beauty_nails', 'Beauty - Nails'), ('beauty_makeup', 'Beauty - Makeup'), ('beauty_skin', 'Beauty - Skin'), ('cleaning_tidy', 'Cleaning - Tidy Up'), ('cleaning_deep', 'Cleaning - Deep Clean'), ('pet_care_walk', 'Pet Care - Dog Walk'), ('pet_care_sit', 'Pet Care - Petsit'), ('car_care_wash', 'Car Care - Wash/Wax'), ('car_care_detail', 'Car Care - Detail'), ('errands', 'Errands'), ('handyman', 'Handyman')], default='beauty', max_length=20),
        ),
    ]
