# Generated by Django 4.2.7 on 2025-05-14 19:57

from django.db import migrations, models
import uuid

def update_appointment_ids(apps, schema_editor):
    """Update appointment IDs to UUID values"""
    Appointment = apps.get_model('main_app', 'Appointment')
    db_alias = schema_editor.connection.alias
    
    # Get all appointments
    appointments = Appointment.objects.using(db_alias).all()
    
    # Update IDs with UUIDs
    for appointment in appointments:
        appointment.id = uuid.uuid4()
        appointment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_appointment_address_line1_appointment_address_line2_and_more'),
    ]

    operations = [
        # First manually alter ID field to allow UUIDs
        migrations.RunSQL(
            sql="""
            ALTER TABLE main_app_appointment 
            ALTER COLUMN id TYPE uuid USING (uuid_generate_v4());
            """,
            reverse_sql="""
            ALTER TABLE main_app_appointment 
            ALTER COLUMN id TYPE integer;
            """
        ),
        
        # Populate with UUIDs
        migrations.RunPython(update_appointment_ids),
    ]
