# Generated by Django 5.2.1 on 2025-05-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_appointment_address_line1_appointment_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='address_line2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
