# Generated by Django 4.2.7 on 2025-05-14 21:25

from django.db import migrations
from django.contrib.gis.db import models as gis_models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_appointment_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='business_location',
            field=gis_models.PointField(blank=True, geography=True, null=True),
        ),
    ] 