# Generated by Django 4.2.7 on 2025-05-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_add_business_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximityDiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier1_distance', models.IntegerField(default=200)),
                ('tier2_min_distance', models.IntegerField(default=200)),
                ('tier2_max_distance', models.IntegerField(default=600)),
                ('tier3_min_distance', models.IntegerField(default=600)),
                ('tier3_max_distance', models.IntegerField(default=1760)),
                ('tier4_min_distance', models.IntegerField(default=1760)),
                ('tier4_max_distance', models.IntegerField(default=5280)),
                ('tier1_1appt_discount', models.IntegerField(default=15)),
                ('tier1_2appt_discount', models.IntegerField(default=20)),
                ('tier1_3appt_discount', models.IntegerField(default=25)),
                ('tier1_4appt_discount', models.IntegerField(default=30)),
                ('tier1_5appt_discount', models.IntegerField(default=35)),
                ('tier2_1appt_discount', models.IntegerField(default=12)),
                ('tier2_2appt_discount', models.IntegerField(default=15)),
                ('tier2_3appt_discount', models.IntegerField(default=18)),
                ('tier2_4appt_discount', models.IntegerField(default=21)),
                ('tier2_5appt_discount', models.IntegerField(default=24)),
                ('tier3_1appt_discount', models.IntegerField(default=10)),
                ('tier3_2appt_discount', models.IntegerField(default=11)),
                ('tier3_3appt_discount', models.IntegerField(default=12)),
                ('tier3_4appt_discount', models.IntegerField(default=13)),
                ('tier3_5appt_discount', models.IntegerField(default=14)),
                ('tier4_1appt_discount', models.IntegerField(default=5)),
                ('tier4_2appt_discount', models.IntegerField(default=6)),
                ('tier4_3appt_discount', models.IntegerField(default=7)),
                ('tier4_4appt_discount', models.IntegerField(default=8)),
                ('tier4_5appt_discount', models.IntegerField(default=9)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_config', to='main_app.serviceprovider')),
            ],
        ),
    ] 