# Generated by Django 5.2.1 on 2025-05-14 21:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_proximitydiscountconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
