# Generated by Django 5.2.1 on 2025-05-14 22:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_appointment_location_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='address_line1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='address_line2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_radius',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
